// import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";
import styles from "../../../styles/Home.module.css";
export default function Post({ post }) {
  // const router = useRouter();
  // const { id } = router.query;
  return (
    <section className={styles.main}>
      <Head>
        <title>Attai Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>{post.title}</h2>
      <p>{post.body}</p>
      <button>
        <Link href="/posts">&larr; Go Back</Link>
      </button>
    </section>
  );
}

// Get data at request time
// export const getServerSideProps = async (context) => {
//   const res = await fetch(
//     `https://jsonplaceholder.typicode.com/posts/${context.params.id}`
//   );
//   const post = await res.json();

//   return {
//     props: {
//       post,
//     },
//   };
// };

// Get data at build time
export const getStaticProps = async (context) => {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/posts/${context.params.id}`
  );
  const post = await res.json();

  return {
    props: {
      post,
    },
  };
};

export const getStaticPaths = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts`);
  const posts = await res.json();

  const ids = posts.map((post) => post.id);
  const paths = ids.map((id) => ({
    params: {
      id: id.toString(),
    },
  }));

  return {
    paths,
    fallback: false,
  };
};
